version: '3.7'

services: 
    
    database:
        image: mongo:4.4.18
        ports: 
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DEFAULT_DB}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
    
    database-admin:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PWD}
            - ME_CONFIG_MONGODB_SERVER=database
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PWD}

    datalogger:
        build: .
        volumes:
          -  ./log:/datalogger/log
          - datalogger-dbdata:/data/db

volumes:
    datalogger-dbdata: